# Ruwan Thilakaratne
# PHIRE Data analysis libraries

# libraries
#packages
memory.limit(size=100000)
library(haven)
library(dplyr)
library(stringr)
library(ggplot2)
library(scales)
library(tableone)
library(splines)
library(tidycensus)
library(tidyverse)
library(lubridate)
library(AER)
library(knitr)
library(data.table)
library(biglm)
library(speedglm)
library(sp)
library(leaflet)
library(raster)
library(rgdal)
library(geosphere)
library(rgeos)
library(wesanderson)
library(stats)
library(devtools)
library(sf)
library(lme4)
library(glmmADMB)
library(weathermetrics)
library(effects)
library(sjPlot)
library(broom.mixed)
library(dlnm)
library(forecast)
library(readxl)
library(spdep)

